server:
  port: 8080
  servlet:
    context-path: /inkCase-api

lbj:
  jwt:
    header: Authorization
    expire: 604800 # 7天，s为单位
    secret: TUrnEmnc2V6iJA/G0o5FZnobyB6HsoKzPr94LrgVTaNFNbdvoxm17QR8ufE1TKOgwt9RzIsIRUnCAPuI0MmHaQ==

spring:
  application:
    name: inkCase-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.41.0.92:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  security:
#    oauth2:
#      client:
#        registration:
#          login-client:
#            client-id: inkCase
#            client-secret: inkCase
#            provider: inkCase
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: read,write
#            client-authentication-method: basic
#            authorization-grant-type: authorization_code
#            client-name: inkCase
#
#      authorization-server:
#        client:
#          client-id: inkCase
#          client-secret: inkCase
#          authorization-grant-types: password,authorization_code,refresh_token
#          redirect-uri: http://192.168.37.137:8080/login/oauth2/code/
#          scopes: read,write
    user:
      name: admin
      password: admin
  mail:
    protocol: smtps
    #配置smtp服务主机地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994
    host: smtp.163.com
    #发送者邮箱
    username: lubaijia2024@163.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: VQFCDHCZNADVKAXO
    #端口号465或587
    port: 465
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  data:
    redis:
      host: 110.41.0.92
      port: 6379
      password: 123456
      database: 0
  cache:
    redis:
      time-to-live: 180000
  mvc:
    static-path-pattern: /**

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${me.upload.path}

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # 打开日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 雪花算法
      id-type: ASSIGN_ID

me:
  upload:
    path: /img/
#  浏览量
  view:
    count: 30
